apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrootd-tester
  namespace: aaas
  labels:
    app: xrootd-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrootd-tester
  template:
    metadata:
      labels:
        app: xrootd-tester
    spec:
      volumes:
      - name: x509-data
        emptyDir: {}
      - name: x509-certs-volume
        secret:
          secretName: x509-secret
          items:
          - key: userkey
            path: userkey.pem
            mode: 256 
          - key: usercert
            path: usercert.pem

      containers:
      - name: xrootd-tester
        image: atlasanalyticsservice/origin-tester:latest
        imagePullPolicy: "Always"
        command: ["python"]
        args: ["xroot_test.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: RUCIO_ACCOUNT
          value: "ivukotic"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: es-auth
              key: es_user
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: es-auth
              key: es_pass
        - name: ES_HOST
          valueFrom:
            secretKeyRef:
              name: es-auth
              key: es_host
        volumeMounts:
        - name: x509-data
          mountPath: "/etc/grid-security/"
          readOnly: false
        - name: x509-certs-volume
          mountPath: "/etc/grid-certs/"
          readOnly: true

      - name: x509
        image: atlasanalyticsservice/origin-tester:latest
        imagePullPolicy: "Always"
        command: ["./run_x509_updater.sh"]
        volumeMounts:
        - name: x509-data
          mountPath: "/etc/grid-security/"
          readOnly: false
        - name: x509-certs-volume
          mountPath: "/etc/grid-certs/"
          readOnly: true
          